version: '3.9'

services:
  rabbitmq-node:
    image: rabbitmq:3-management
    container_name: rabbitmq-node
    hostname: rabbitmq-node
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - $PWD/storage/rabbitmq-node-1:/var/lib/rabbitmq
    environment:
      - RABBITMQ_ERLANG_COOKIE=cluster_cookie
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=Admin@123   